logging:
  version: 1
  disable_existing_loggers: true
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: ext://sys.stdout
  formatters:
    standard:
      format: "[%(asctime)s] [%(levelname)s] %(message)s"
      datefmt: "%H:%M:%S"
  loggers:
    "":
      level: INFO
      handlers:
        - default
